spring:
  datasource:
    url: jdbc:mysql://101.43.73.38:3306/pollenweb?useUnicode=true&characterEncoding=UTF-8
    username: PollenWeb
    password: pollenweb
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  mvc:
    static-path-pattern: /static/*
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: html
server:
  8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/pollen/pollenweb/mapper/xml/*.xml

file:
    fileUploadDir: /Users/macmini/Downloads/testfile